version: "3"
services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Mypassword21&
      MYSQL_DATABASE: task_manager
